version: 0.0.0
description: Pooltogether community nft birbwatcher
repository: https://github.com/float-capital/birbwatcher
networks:
  - id: 1
    rpc_url: https://eth.llamarpc.com
    start_block: 14838105
    contracts:
      - name: Pooly
        abi_file_path: null
        address:
          - "0x90B3832e2F2aDe2FE382a911805B6933C056D6ed"
          - "0x3545192b340F50d77403DC0A64cf2b32F03d00A9"
          - "0x5663e3E096f1743e77B8F71b5DE0CF9Dfd058523"
        handler: src/EventHandlers.ts
        events:
          - event: "event NFTInitialized(string name, string symbol, uint128 nftPrice, uint32 maxNFT, uint32 maxMint, uint32 startTimestamp, uint32 endTimestamp, address owner)"
            requiredEntities: []
          - event: "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
            requiredEntities:
              - name: "User"
                labels:
                  - "userFrom"
                  - "userTo"
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
      - name: PoolyPfers
        abi_file_path: null
        address: "0xBCC664B1E6848caba2Eb2f3dE6e21F81b9276dD8" # 15882116
        handler: src/EventHandlers.ts
        events:
          - event: "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
            requiredEntities:
              - name: "User"
                labels:
                  - "userFrom"
                  - "userTo"
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
      - name: ChuckBurgeronNFT
        abi_file_path: null
        address: "0x9aF7B3cfCa8a0d0feD9A8C9b77f6088cB1bbF791" # 16302826
        handler: src/EventHandlers.ts
        events:
          - event: "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
            requiredEntities:
              - name: "User"
                labels:
                  - "userFrom"
                  - "userTo"
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
  - id: 10
    rpc_url: https://rpc.ankr.com/optimism
    start_block: 22228546
    contracts:
      - name: PooltogetherCoinbase
        abi_file_path: null
        address: "0xc10baAd4D7a0C3574d50FA606666EB7De176c7E6"
        handler: src/EventHandlers.ts
        events:
          - event: "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
            requiredEntities:
              - name: "User"
                labels:
                  - "userFrom"
                  - "userTo"
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
  - id: 137
    rpc_url: https://polygon-rpc.com
    start_block: 25977052
    contracts:
      - name: PoolParty
        abi_file_path: null
        address: "0x841918849e6784d7e643837ad59571ea1fc5000b"
        handler: src/EventHandlers.ts
        events:
          - event: "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
            requiredEntities:
              - name: "User"
                labels:
                  - "userFrom"
                  - "userTo"
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
